server:
  port: 8080
spring:
  application:
    name: shrioTest
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.98.255.98:3306/shrio?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.liuchen.entity
  mapper-locations: classpath:mapper/*.xml





logging:
  level:
    com.liuchen.shriotest:
      shrio:
        mapper: debug



jwt:
  config:
    ttl: 100000
    key: shrio